### ISSUE TITLE
Todo before submit

### ISSUE THREAD

**Issue by mariadaan** [AtibQur/Transcendence#130]
- [x] remove .env
- [x] replace dockerfile
- [x] remove console.logs
- [x] remove dead code
- [x] make dummy database
- [x] prisma migrate in dockerfile, not just generate
